### PR TITLE
Create Fat JAR

### PR DESCRIPTION
**Pull request by kiview**
The current version works, but we should clean up the `pom.xml` a little bit more.

The first step for fixing #12.

### CODE REVIEW

**Comment by moekappels** [comment]
ok. so I ve read the files. I understand some of it. I will ignore this pull request for now and continue with the current Main class.

**Comment by kiview** [comment]
@moekappels If you understand some parts of it, what are the parts you don't understand? I'd be happy to explain them.

**Comment by moekappels** [comment]
ok. I ve read up on shade.
mvn shade:shade didnt work for me because some main artifact was missing.
mvn package however did work and I can now execute the program from /shade by using:
java -jar BloxbergCacheCreator.jar 
what do you mean with additional clean up of the pom.xml? 
This code already works for me.

**Comment by kiview** [comment]
Maybe `mvn shade:shade` was not working, since it did not have the correct lifecycle hooks. If you use the main Maven lifecycle methods (such as `mvn package`), you can make sure everything is executed in the correct order.

Cleaning up is just small refactorings for extracting e.g. JavaFX version into single property, will do it later :slightly_smiling_face:.

**Comment by moekappels** [comment]
test

**Comment by moekappels** [comment]
cool.

**Comment by kiview** [comment]
Finished cleaning up the POM file and also upgraded all dependencies and Java to version 14.

**Pull request merged**
