### PR TITLE
Connect via websocket

### PR DESCRIPTION
**Pull request by Mschnuff**
### **Work in Progress**
First attempt to connect to the bloxberg-network via websocket instead of http. 
Existing code can be used as a base to work on [issue 41](https://github.com/internet-sicherheit/ethereum-cache-creator/issues/41). 
throws WebsocketNotConnectedException (build failure is deliberate)
textoutput indicates that the websocket is _not open_:

```
[INFO] Running de.internetsicherheit.brl.bloxberg.cache.ethereum.BloxbergClientTests
websocket socket: Socket[addr=core.bloxberg.org/130.183.206.234,port=80,localport=57242]
websocket is open: false
successfully build Web3j object.
```

I am actually not sure how to proceed from here. I try to read up on this topic a little bit.

### CODE REVIEW

**Comment by kiview** [comment]
Please try the following URLs:
```
https://websockets.bloxberg.org
wss://websockets.bloxberg.org
```

**Comment by moekappels** [comment]
running with ```wss://websockets.bloxberg.org``` gives following result:
```[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 61.953 s <<< FAILURE! - in de.internetsicherheit.brl.bloxberg.cache.ethereum.BloxbergClientTests
[ERROR] blockNumber  Time elapsed: 60.188 s  <<< ERROR!
java.io.IOException: Request with id 2 timed out```

**Comment by kiview** [comment]
So the `wss://websockets.bloxberg.org` is obviously the correct one. Check why timeout happens, or if the API becomes different, potentially asynchronous or something.

**Comment by moekappels** [comment]
I notice java wants to use port 80 or 443 (these are the defaults). chinmay keeps telling me about port 8546. with local parity I get this result:
```
[INFO] Running BlockDataExtractorTest
websocket socket: Socket[addr=localhost/127.0.0.1,port=8546,localport=34172]
websocket is open: true
successfully build Web3j object.
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.321 s - in BlockDataExtractorTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   BloxbergClientTests.blockNumber » IO Request with id 2 timed out
[INFO] 
[ERROR] Tests run: 14, Failures: 0, Errors: 1, Skipped: 0
```
I notice that the websocket is open. but there is no data to extract.

**Comment by kiview** [comment]
Instead of testing against a local empty parity (is it empty or not?), I recommend testing against Ethereum mainnet, which can be done using Infura:
https://infura.io/product

I did this for checking the uncles code.

**Comment by kiview** [comment]
Bloxberg people said, they assume it should run on port 8546.

**Comment by moekappels** [comment]
yeah ok so with infura i get the same errors. requests timing out.

**Comment by kiview** [comment]
Alright, this gives us some indication that the code is the problem and not the Websocket service from bloxberg.

There are different ways to use WebSockets, blocking or non-blocking, I assume it is related. See these tests from Web3j to get some examples:
https://github.com/web3j/web3j/blob/63facc546031c7ea2d9825b3100559ce459c202d/core/src/test/java/org/web3j/protocol/websocket/WebSocketServiceTest.java

**Comment by moekappels** [comment]
ok so that s weird if i add a listener to the websocketclient I do get a message with the version number for both bloxberg and infura. So the websocketclient is responding in some way: 

- bloxberg: Parity-Ethereum//v2.6.6-beta-5162bc2-20191205/x86_64-linux-gnu/rustc1.39.0
- infura: Geth/v1.9.9-omnibus-e320ae4c-20191206/linux-amd64/go1.13.4

**Comment by kiview** [comment]
For me this means, Websocket connection works, you now just need to identify the programming model to interact with it correctly from web3j.

**Comment by moekappels** [comment]
Since this is based on an outdated master branch and the commits became increasingly chaotic and unreadable, I opened a new pull request with cleaner code:
[pull request #46](https://github.com/internet-sicherheit/ethereum-cache-creator/pull/46)

**Comment by Mschnuff** [comment]
should we close this? it is confusing to have 2 pull requests open that sound so similar.

**Pull request closed without merging**
